package co.yedam.teamproject.member.web;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import co.yedam.teamproject.common.SendMail;
import co.yedam.teamproject.common.ViewResolve;
import co.yedam.teamproject.member.service.MemberService;
import co.yedam.teamproject.member.service.MemberVO;
import co.yedam.teamproject.member.serviceImpl.MemberServiceImpl;

@WebServlet("/findid.do")
public class FindId extends HttpServlet {
	private static final long serialVersionUID = 1L;

    public FindId() {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		MemberService dao = new MemberServiceImpl();
		MemberVO vo = new MemberVO();
		
		vo.setMemberName(request.getParameter("findIdName"));
		vo.setMemberEmail(request.getParameter("findIdEmail"));
		vo = dao.memberSelectEmail(vo);
		
		String str = "";
		if (vo != null) {
			String to = "workroom_km@naver.com";
					//vo.getMemberEmail();
			
			String title = "아이디 찾기";
			String content = "<!DOCTYPE html><html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><head>\r\n"
					+ "  <title> Welcome to [Coded Mails] </title>\r\n"
					+ "  <!--[if !mso]><!-- -->\r\n"
					+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n"
					+ "  <!--<![endif]-->\r\n"
					+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n"
					+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n"
					+ "  <style type=\"text/css\">\r\n"
					+ "    #outlook a {\r\n"
					+ "      padding: 0;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    body {\r\n"
					+ "      margin: 0;\r\n"
					+ "      padding: 0;\r\n"
					+ "      -webkit-text-size-adjust: 100%;\r\n"
					+ "      -ms-text-size-adjust: 100%;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    table,\r\n"
					+ "    td {\r\n"
					+ "      border-collapse: collapse;\r\n"
					+ "      mso-table-lspace: 0pt;\r\n"
					+ "      mso-table-rspace: 0pt;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    img {\r\n"
					+ "      border: 0;\r\n"
					+ "      height: auto;\r\n"
					+ "      line-height: 100%;\r\n"
					+ "      outline: none;\r\n"
					+ "      text-decoration: none;\r\n"
					+ "      -ms-interpolation-mode: bicubic;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    p {\r\n"
					+ "      display: block;\r\n"
					+ "      margin: 13px 0;\r\n"
					+ "    }\r\n"
					+ "  </style>\r\n"
					+ "  <!--[if mso]>\r\n"
					+ "        <xml>\r\n"
					+ "        <o:OfficeDocumentSettings>\r\n"
					+ "          <o:AllowPNG/>\r\n"
					+ "          <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
					+ "        </o:OfficeDocumentSettings>\r\n"
					+ "        </xml>\r\n"
					+ "        <![endif]-->\r\n"
					+ "  <!--[if lte mso 11]>\r\n"
					+ "        <style type=\"text/css\">\r\n"
					+ "          .mj-outlook-group-fix { width:100% !important; }\r\n"
					+ "        </style>\r\n"
					+ "        <![endif]-->\r\n"
					+ "  <!--[if !mso]><!-->\r\n"
					+ "  <link href=\"https://fonts.googleapis.com/css?family=Nunito:100,400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n"
					+ "  <style type=\"text/css\">\r\n"
					+ "    @import url(https://fonts.googleapis.com/css?family=Nunito:100,400,700);\r\n"
					+ "  </style>\r\n"
					+ "  <!--<![endif]-->\r\n"
					+ "  <style type=\"text/css\">\r\n"
					+ "    @media only screen and (min-width:480px) {\r\n"
					+ "      .mj-column-per-100 {\r\n"
					+ "        width: 100% !important;\r\n"
					+ "        max-width: 100%;\r\n"
					+ "      }\r\n"
					+ "    }\r\n"
					+ "  </style>\r\n"
					+ "  <style type=\"text/css\">\r\n"
					+ "    @media only screen and (max-width:480px) {\r\n"
					+ "      table.mj-full-width-mobile {\r\n"
					+ "        width: 100% !important;\r\n"
					+ "      }\r\n"
					+ "\r\n"
					+ "      td.mj-full-width-mobile {\r\n"
					+ "        width: auto !important;\r\n"
					+ "      }\r\n"
					+ "    }\r\n"
					+ "  </style>\r\n"
					+ "  <style type=\"text/css\">\r\n"
					+ "    a,\r\n"
					+ "    span,\r\n"
					+ "    td,\r\n"
					+ "    th {\r\n"
					+ "      -webkit-font-smoothing: antialiased !important;\r\n"
					+ "      -moz-osx-font-smoothing: grayscale !important;\r\n"
					+ "    }\r\n"
					+ "  </style>\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body style=\"background-color:#eaeaea;\">\r\n"
					+ "  <div style=\"display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;\"> Preview - Welcome to Coded Mails </div>\r\n"
					+ "  <div style=\"background-color:#eaeaea;\">\r\n"
					+ "    <!--[if mso | IE]>\r\n"
					+ "      <table\r\n"
					+ "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"\r\n"
					+ "      >\r\n"
					+ "        <tr>\r\n"
					+ "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
					+ "      <![endif]-->\r\n"
					+ "    <div style=\"margin:0px auto;max-width:600px;\">\r\n"
					+ "      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\r\n"
					+ "        <tbody>\r\n"
					+ "          <tr>\r\n"
					+ "            <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;\">\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                \r\n"
					+ "        <tr>\r\n"
					+ "      \r\n"
					+ "            <td\r\n"
					+ "               class=\"\" style=\"vertical-align:top;width:600px;\"\r\n"
					+ "            >\r\n"
					+ "          <![endif]-->\r\n"
					+ "              <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">\r\n"
					+ "                  <tbody><tr>\r\n"
					+ "                    <td style=\"font-size:0px;word-break:break-word;\">\r\n"
					+ "                      <!--[if mso | IE]>\r\n"
					+ "    \r\n"
					+ "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td height=\"20\" style=\"vertical-align:top;height:20px;\">\r\n"
					+ "      \r\n"
					+ "    <![endif]-->\r\n"
					+ "                      <div style=\"height:20px;\">   </div>\r\n"
					+ "                      <!--[if mso | IE]>\r\n"
					+ "    \r\n"
					+ "        </td></tr></table>\r\n"
					+ "      \r\n"
					+ "    <![endif]-->\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                </tbody></table>\r\n"
					+ "              </div>\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "            </td>\r\n"
					+ "          \r\n"
					+ "        </tr>\r\n"
					+ "      \r\n"
					+ "                  </table>\r\n"
					+ "                <![endif]-->\r\n"
					+ "            </td>\r\n"
					+ "          </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "      </table>\r\n"
					+ "    </div>\r\n"
					+ "    <!--[if mso | IE]>\r\n"
					+ "          </td>\r\n"
					+ "        </tr>\r\n"
					+ "      </table>\r\n"
					+ "      \r\n"
					+ "      <table\r\n"
					+ "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"\r\n"
					+ "      >\r\n"
					+ "        <tr>\r\n"
					+ "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
					+ "      \r\n"
					+ "        <v:rect  style=\"width:600px;\" xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" stroke=\"false\">\r\n"
					+ "        <v:fill  origin=\"0.5, 0\" position=\"0.5, 0\" src=\"https://images.unsplash.com/photo-1596146828437-d845f3b3235b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80\" type=\"tile\" />\r\n"
					+ "        <v:textbox style=\"mso-fit-shape-to-text:true\" inset=\"0,0,0,0\">\r\n"
					+ "      <![endif]-->\r\n"
					+ "    <div style=\"background:url(https://images.unsplash.com/photo-1596146828437-d845f3b3235b?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=80) top center / cover no-repeat;margin:0px auto;border-radius:20px 20px 0 0;max-width:600px;\">\r\n"
					+ "      <div style=\"line-height:0;font-size:0;\">\r\n"
					+ "        <table align=\"center\" background=\"https://images.unsplash.com/photo-1596146828437-d845f3b3235b?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=80\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:url(https://images.unsplash.com/photo-1596146828437-d845f3b3235b?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=80) top center / cover no-repeat;width:100%;border-radius:20px 20px 0 0;\">\r\n"
					+ "          <tbody>\r\n"
					+ "            <tr>\r\n"
					+ "              <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;\">\r\n"
					+ "                <!--[if mso | IE]>\r\n"
					+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                \r\n"
					+ "        <tr>\r\n"
					+ "      \r\n"
					+ "            <td\r\n"
					+ "               class=\"\" style=\"vertical-align:top;width:600px;\"\r\n"
					+ "            >\r\n"
					+ "          <![endif]-->\r\n"
					+ "                <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">\r\n"
					+ "                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">\r\n"
					+ "                    <tbody><tr>\r\n"
					+ "                      <td align=\"center\" style=\"font-size:0px;padding:8px 0;word-break:break-word;\">\r\n"
					+ "                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">\r\n"
					+ "                          <tbody>\r\n"
					+ "                            <tr>\r\n"
					+ "                              <td style=\"width:150px;\">\r\n"
					+ "                                <img height=\"auto\" src=\"https://codedmails.com/images/logo-white.png\" style=\"border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:16px;\" width=\"150\" />\r\n"
					+ "                              </td>\r\n"
					+ "                            </tr>\r\n"
					+ "                          </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                      </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                    <tr>\r\n"
					+ "                      <td style=\"font-size:0px;word-break:break-word;\">\r\n"
					+ "                        <!--[if mso | IE]>\r\n"
					+ "    \r\n"
					+ "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td height=\"250\" style=\"vertical-align:top;height:250px;\">\r\n"
					+ "      \r\n"
					+ "    <![endif]-->\r\n"
					+ "                        <div style=\"height:250px;\">   </div>\r\n"
					+ "                        <!--[if mso | IE]>\r\n"
					+ "    \r\n"
					+ "        </td></tr></table>\r\n"
					+ "      \r\n"
					+ "    <![endif]-->\r\n"
					+ "                      </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                  </tbody></table>\r\n"
					+ "                </div>\r\n"
					+ "                <!--[if mso | IE]>\r\n"
					+ "            </td>\r\n"
					+ "          \r\n"
					+ "        </tr>\r\n"
					+ "      \r\n"
					+ "                  </table>\r\n"
					+ "                <![endif]-->\r\n"
					+ "              </td>\r\n"
					+ "            </tr>\r\n"
					+ "          </tbody>\r\n"
					+ "        </table>\r\n"
					+ "      </div>\r\n"
					+ "    </div>\r\n"
					+ "    <!--[if mso | IE]>\r\n"
					+ "        </v:textbox>\r\n"
					+ "      </v:rect>\r\n"
					+ "    \r\n"
					+ "          </td>\r\n"
					+ "        </tr>\r\n"
					+ "      </table>\r\n"
					+ "      \r\n"
					+ "      <table\r\n"
					+ "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"\r\n"
					+ "      >\r\n"
					+ "        <tr>\r\n"
					+ "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
					+ "      <![endif]-->\r\n"
					+ "    <div style=\"background:#ffffff;background-color:#ffffff;margin:0px auto;border-radius:0 0 20px 20px;max-width:600px;\">\r\n"
					+ "      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#ffffff;background-color:#ffffff;width:100%;border-radius:0 0 20px 20px;\">\r\n"
					+ "        <tbody>\r\n"
					+ "          <tr>\r\n"
					+ "            <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;\">\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                \r\n"
					+ "        <tr>\r\n"
					+ "      \r\n"
					+ "            <td\r\n"
					+ "               class=\"\" style=\"vertical-align:top;width:600px;\"\r\n"
					+ "            >\r\n"
					+ "          <![endif]-->\r\n"
					+ "              <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">\r\n"
					+ "                  <tbody><tr>\r\n"
					+ "                    <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <div style=\"font-family:Nunito, Helvetica, Arial, sans-serif;font-size:18px;font-weight:400;line-height:30px;text-align:left;color:#54595f;\">\r\n"
					+ "                        <h2 style=\"margin: 0; line-height: normal; font-weight: bold; font-size: 20px;\"> Hey Mike,</h2>\r\n"
					+ "                      </div>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                  <tr>\r\n"
					+ "                    <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <div style=\"font-family:Nunito, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:22px;text-align:left;color:#54595f;\">\r\n"
					+ "                        <h1 style=\"margin: 0; font-size: 24px; line-height: normal; font-weight: bold;\">You have a new support message.</h1>\r\n"
					+ "                      </div>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                  <tr>\r\n"
					+ "                    <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <div style=\"font-family:Nunito, Helvetica, Arial, sans-serif;font-size:16px;font-style:italic;font-weight:400;line-height:22px;text-align:left;color:#54595f;\">\r\n"
					+ "                        <p style=\"margin: 0;\"><strong> Message </strong> : It has survived not only five centuries, but the normal behaviour of the loream is not about just the values you get from the mathamatical equation but also... </p>\r\n"
					+ "                      </div>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                  <tr>\r\n"
					+ "                    <td align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\">\r\n"
					+ "                        <tbody><tr>\r\n"
					+ "                          <td align=\"center\" bgcolor=\"#54595f\" role=\"presentation\" style=\"border:none;border-radius:30px;cursor:auto;mso-padding-alt:10px 25px;background:#54595f;\" valign=\"middle\">\r\n"
					+ "                            <a href=\"https://google.com\" style=\"display: inline-block; background: #54595f; color: white; font-family: Nunito, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 30px; margin: 0; text-decoration: none; text-transform: none; padding: 10px 25px; mso-padding-alt: 0px; border-radius: 30px;\" target=\"_blank\"> Read the complete message </a>\r\n"
					+ "                          </td>\r\n"
					+ "                        </tr>\r\n"
					+ "                      </tbody></table>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                  <tr>\r\n"
					+ "                    <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <div style=\"font-family:Nunito, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:22px;text-align:left;color:#54595f;\">If you have any questions simply reply to this email and we would be more than happy to reply. :)</div>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                </tbody></table>\r\n"
					+ "              </div>\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "            </td>\r\n"
					+ "          \r\n"
					+ "        </tr>\r\n"
					+ "      \r\n"
					+ "                  </table>\r\n"
					+ "                <![endif]-->\r\n"
					+ "            </td>\r\n"
					+ "          </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "      </table>\r\n"
					+ "    </div>\r\n"
					+ "    <!--[if mso | IE]>\r\n"
					+ "          </td>\r\n"
					+ "        </tr>\r\n"
					+ "      </table>\r\n"
					+ "      \r\n"
					+ "      <table\r\n"
					+ "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"\r\n"
					+ "      >\r\n"
					+ "        <tr>\r\n"
					+ "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
					+ "      <![endif]-->\r\n"
					+ "    <div style=\"margin:0px auto;max-width:600px;\">\r\n"
					+ "      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\r\n"
					+ "        <tbody>\r\n"
					+ "          <tr>\r\n"
					+ "            <td style=\"direction:ltr;font-size:0px;padding:20px 0;padding-bottom:0px;text-align:center;\">\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                \r\n"
					+ "        <tr>\r\n"
					+ "      \r\n"
					+ "            <td\r\n"
					+ "               class=\"\" style=\"vertical-align:top;width:600px;\"\r\n"
					+ "            >\r\n"
					+ "          <![endif]-->\r\n"
					+ "              <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">\r\n"
					+ "                  <tbody><tr>\r\n"
					+ "                    <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <div style=\"font-family:Nunito, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:22px;text-align:center;color:#54595f;\"><a href=\"#\" style=\"color: #54595f; display: inline-block; text-decoration: none;\">\r\n"
					+ "                          <img src=\"https://codedmails.com/images/google-play.png\" alt=\"play-store-logo\" width=\"150px\" />\r\n"
					+ "                        </a>\r\n"
					+ "                        <a href=\"#\" style=\"color: #54595f; display: inline-block; text-decoration: none;\">\r\n"
					+ "                          <img src=\"https://codedmails.com/images/app-store.png\" alt=\"app-store-logo\" width=\"150px\" />\r\n"
					+ "                        </a></div>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                </tbody></table>\r\n"
					+ "              </div>\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "            </td>\r\n"
					+ "          \r\n"
					+ "        </tr>\r\n"
					+ "      \r\n"
					+ "                  </table>\r\n"
					+ "                <![endif]-->\r\n"
					+ "            </td>\r\n"
					+ "          </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "      </table>\r\n"
					+ "    </div>\r\n"
					+ "    <!--[if mso | IE]>\r\n"
					+ "          </td>\r\n"
					+ "        </tr>\r\n"
					+ "      </table>\r\n"
					+ "      \r\n"
					+ "      <table\r\n"
					+ "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"\r\n"
					+ "      >\r\n"
					+ "        <tr>\r\n"
					+ "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
					+ "      <![endif]-->\r\n"
					+ "    <div style=\"margin:0px auto;max-width:600px;\">\r\n"
					+ "      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\r\n"
					+ "        <tbody>\r\n"
					+ "          <tr>\r\n"
					+ "            <td style=\"direction:ltr;font-size:0px;padding:20px 0;padding-top:0px;text-align:center;\">\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                \r\n"
					+ "        <tr>\r\n"
					+ "      \r\n"
					+ "            <td\r\n"
					+ "               class=\"\" style=\"vertical-align:top;width:600px;\"\r\n"
					+ "            >\r\n"
					+ "          <![endif]-->\r\n"
					+ "              <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">\r\n"
					+ "                  <tbody><tr>\r\n"
					+ "                    <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <div style=\"font-family:Nunito, Helvetica, Arial, sans-serif;font-size:14px;font-weight:400;line-height:18px;text-align:center;color:#54595f;\">123 Medalling Jr., Suite 100, Parrot Park, CA 12345<br /> © 2020 [Coded Mails] Inc.</div>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                  <tr>\r\n"
					+ "                    <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
					+ "                      <div style=\"font-family:Nunito, Helvetica, Arial, sans-serif;font-size:14px;font-weight:400;line-height:18px;text-align:center;color:#54595f;\">Update your <a href=\"https://google.com\" style=\"color: #54595f; text-decoration: underline;\">email preferences</a> to choose the types of emails you receive, or you can <a href=\"https://google.com\" style=\"color: #54595f; text-decoration: underline;\"> unsubscribe </a>from all future emails.</div>\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                </tbody></table>\r\n"
					+ "              </div>\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "            </td>\r\n"
					+ "          \r\n"
					+ "        </tr>\r\n"
					+ "      \r\n"
					+ "                  </table>\r\n"
					+ "                <![endif]-->\r\n"
					+ "            </td>\r\n"
					+ "          </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "      </table>\r\n"
					+ "    </div>\r\n"
					+ "    <!--[if mso | IE]>\r\n"
					+ "          </td>\r\n"
					+ "        </tr>\r\n"
					+ "      </table>\r\n"
					+ "      \r\n"
					+ "      <table\r\n"
					+ "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"\r\n"
					+ "      >\r\n"
					+ "        <tr>\r\n"
					+ "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
					+ "      <![endif]-->\r\n"
					+ "    <div style=\"margin:0px auto;max-width:600px;\">\r\n"
					+ "      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\r\n"
					+ "        <tbody>\r\n"
					+ "          <tr>\r\n"
					+ "            <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;\">\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "                \r\n"
					+ "        <tr>\r\n"
					+ "      \r\n"
					+ "            <td\r\n"
					+ "               class=\"\" style=\"vertical-align:top;width:600px;\"\r\n"
					+ "            >\r\n"
					+ "          <![endif]-->\r\n"
					+ "              <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">\r\n"
					+ "                  <tbody><tr>\r\n"
					+ "                    <td style=\"font-size:0px;word-break:break-word;\">\r\n"
					+ "                      <!--[if mso | IE]>\r\n"
					+ "    \r\n"
					+ "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td height=\"1\" style=\"vertical-align:top;height:1px;\">\r\n"
					+ "      \r\n"
					+ "    <![endif]-->\r\n"
					+ "                      <div style=\"height:1px;\">   </div>\r\n"
					+ "                      <!--[if mso | IE]>\r\n"
					+ "    \r\n"
					+ "        </td></tr></table>\r\n"
					+ "      \r\n"
					+ "    <![endif]-->\r\n"
					+ "                    </td>\r\n"
					+ "                  </tr>\r\n"
					+ "                </tbody></table>\r\n"
					+ "              </div>\r\n"
					+ "              <!--[if mso | IE]>\r\n"
					+ "            </td>\r\n"
					+ "          \r\n"
					+ "        </tr>\r\n"
					+ "      \r\n"
					+ "                  </table>\r\n"
					+ "                <![endif]-->\r\n"
					+ "            </td>\r\n"
					+ "          </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "      </table>\r\n"
					+ "    </div>\r\n"
					+ "    <!--[if mso | IE]>\r\n"
					+ "          </td>\r\n"
					+ "        </tr>\r\n"
					+ "      </table>\r\n"
					+ "      <![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "</body></html>";
			
			SendMail sendMail = new SendMail();
			sendMail.sendMail(to, title, content);
			
			str = "findIdSuccess";
		} else {
			str = "findIdFail";
		}
		
		request.setAttribute("findIdmessage", str);
		
		String page = "main/account";
		ViewResolve.forward(request, response, page);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

}
